# Generated by Django 4.1.3 on 2022-11-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(max_length=4),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(max_length=4),
        ),
    ]
