# Generated by Django 4.1.3 on 2022-11-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='note',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
