# Generated by Django 4.1.3 on 2022-11-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petowner',
            name='id',
        ),
        migrations.AlterField(
            model_name='petowner',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petowner',
            name='pet_type',
            field=models.TextField(choices=[('D', 'Dog'), ('C', 'Cat'), ('SA', 'Small Animal'), ('R', 'Reptile'), ('B', 'Bird')]),
        ),
    ]
