# Generated by Django 4.1.3 on 2022-11-26 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petowner',
            old_name='type',
            new_name='pet_type',
        ),
    ]
