# Generated by Django 4.1.3 on 2022-11-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitter',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='petsitter',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='petsitter',
            name='pet_type',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('REP', 'Reptile'), ('SMA', 'Small Animal'), ('BIR', 'Bird')], default='DOG', max_length=3),
        ),
    ]
