# Generated by Django 4.1.3 on 2022-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitter',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
