# Generated by Django 4.1.3 on 2022-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_petsitter_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitter',
            name='image',
            field=models.TextField(blank=True, default='https://i.imgur.com/HQTMGNs.jpg'),
        ),
    ]
