# Generated by Django 4.1.3 on 2022-11-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_type_petowner_pet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_day',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
