# Generated by Django 4.1.3 on 2022-11-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_end_time_alter_booking_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsitter',
            name='bio',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
