# Generated by Django 4.1.3 on 2022-11-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_pettype_remove_petsitter_pet_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mango',
        ),
    ]
