# Generated by Django 4.1.3 on 2022-11-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_petsitter_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitter',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
