# Generated by Django 4.1.3 on 2022-11-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_booking_end_day_alter_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
