# Generated by Django 4.1.3 on 2022-11-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_petsitter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsitter',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
