# Generated by Django 4.1.3 on 2022-11-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_booking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_email',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='note',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
