# Generated by Django 4.1.3 on 2022-11-24 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_petsitter_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsitter',
            name='id',
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
