# Generated by Django 4.1.3 on 2022-11-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_petsitter_friday_remove_petsitter_monday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsitter',
            name='bird',
        ),
        migrations.RemoveField(
            model_name='petsitter',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='petsitter',
            name='dog',
        ),
        migrations.RemoveField(
            model_name='petsitter',
            name='reptile',
        ),
        migrations.RemoveField(
            model_name='petsitter',
            name='small_animal',
        ),
        migrations.AddField(
            model_name='petsitter',
            name='pet_type',
            field=models.CharField(default='dog', help_text='Pet types: dog cat small_animal reptile bird', max_length=50),
        ),
        migrations.AlterField(
            model_name='petsitter',
            name='availability',
            field=models.CharField(default='monday', help_text='Days of the week, lower case, separated by a space', max_length=100),
        ),
    ]
