# Generated by Django 4.1.3 on 2022-11-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_petsitter_bird_remove_petsitter_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsitter',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='petsitter',
            name='bird',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petsitter',
            name='cat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petsitter',
            name='dog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petsitter',
            name='reptile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petsitter',
            name='small_animal',
            field=models.BooleanField(default=False),
        ),
    ]
